# Generated by Django 4.2.20 on 2025-04-22 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(help_text='The user associated with this profile.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', help_text='User profile picture or avatar.', null=True, upload_to='avatars/', verbose_name='avatar')),
                ('post_anonymously', models.BooleanField(default=False, help_text="If checked, your username will be hidden in public community posts, showing 'Anonymous' instead.", verbose_name='post_anonymously')),
                ('default_challenge_length', models.PositiveIntegerField(blank=True, choices=[(7, '7 Days'), (14, '14 Days'), (30, '30 Days'), (90, '90 Days')], help_text='Your preferred default duration (in days) when creating a new challenge.', null=True, verbose_name='default_challenge_length')),
                ('enable_global_reminders', models.BooleanField(default=True, help_text='Master setting to enable or disable all daily check-in email reminders.', verbose_name='enable daily check-in notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='profile created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='profile updated')),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
    ]
