# Generated by Django 4.2.20 on 2025-05-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User profile picture or avatar.', null=True, upload_to='avatars/', verbose_name='avatar'),
        ),
    ]
