# Generated by Django 4.2.20 on 2025-04-19 05:23

from django.db import migrations

# function to create initial achievements

def create_initial_achievements(apps, schema_editor):
    # we get the model from the versioned app registry
    # avoids importing directly which might cause issues with historical models.
    Achievement = apps.get_model('challenge', 'Achievement')
    db_alias = schema_editor.connection.alias #needed for update or create

    # define the initial achievements

    achievements_data = [
        {'name': 'First Check-in', 'description': 'Started your journey by checking in for the first time', 'icon': '🟢', 'criteria_type': 'TOTAL_LOGS', 'criteria_value': 1},
        {'name': '3-Day Streak', 'description': 'Stayed clean for 3 consecutive days', 'icon': '🔥', 'criteria_type': 'STREAK', 'criteria_value': 3},
        {'name': '7-Day Winner', 'description': 'Completed a 7-day clean streak', 'icon': '🏅', 'criteria_type': 'STREAK', 'criteria_value': 7},
        {'name': '30 Days Clean', 'description': 'Reached a month without relapse', 'icon': '🌟', 'criteria_type': 'STREAK', 'criteria_value': 30},
        {'name': '90 Day Legend', 'description': 'Completed the ultimate 90-day clean streak', 'icon': '🏆', 'criteria_type': 'STREAK', 'criteria_value': 90},
        {'name': 'Comeback King', 'description': 'Had the courage to be honest and start again after a relapse', 'icon': '🔄', 'criteria_type': 'RELAPSE_LOGGED', 'criteria_value': 1}, # Requires at least 1 relapse log
        # Add any other achievements you want defined initially
        # {'name': 'Journal Starter', 'description': 'Completed your first journal entry', 'icon': '📔', 'criteria_type': 'JOURNAL_ENTRIES', 'criteria_value': 1},
    ]

    # using update or create makes this migration safe to run multiple times
    # it finds an achievement by 'name' or creates a new one
    for data in achievements_data:
        Achievement.objects.update_or_create(
            name=data['name'],
            defaults=data
        )


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_achievements),
    ]
