# Generated by Django 4.2.20 on 2025-04-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_alter_achievement_criteria_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='relapse_text',
            field=models.TextField(blank=True, help_text='Optional text for the relapse reflection.'),
        ),
    ]
