# Generated by Django 4.2.20 on 2025-04-20 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_reflection_relapse_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('JOINED', 'User Joined'), ('CHALLENGE_STARTED', 'Challenge Started'), ('CHALLENGE_COMPLETED', 'Challenge Completed'), ('ACHIEVEMENT_UNLOCKED', 'Achievement Unlocked'), ('RELAPSE_LOGGED', 'Relapse Logged'), ('CLEAN_DAY_LOGGED', 'Clean Day Logged'), ('REFLECTION_ADDED', 'Reflection Added'), ('JOURNAL_ENTRY_ADDED', 'Journal Entry Added'), ('STREAK_MILESTONE', 'Streak Milestone Reached')], default=-12, help_text='The type of event that occurred.', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the event occurred.'),
        ),
    ]
